### ISSUE TITLE
how do you install

### ISSUE THREAD

**Issue by Memopentagone** [Muslim-Programmers/Quran-application#5]
can't install third step not working gives error

**Comment by Memopentagone** [comment]
memo@memo-XPS-8950:~/QuranApp-Linux-main$ mkdir build && cmake ..
mkdir: cannot create directory ‘build’: File exists

**Comment by nxb1t** [comment]
Sorry for the late reply brother, 
Will you re-clone the repo and build again.

I have fixed the readme now,

`mkdir build && cd build && cmake ..`

The `build file exists error is that you have already created a 'build' folder`

![image](https://user-images.githubusercontent.com/95064572/235117169-777ae2ce-04a5-4e38-a5f6-46ad52695656.png)
