### ISSUE TITLE
Hamazatul wasl (ٱ) doesn't render in `README.md`

### ISSUE THREAD

**Issue by iTzVoko** [Muslim-Programmers/Quran-application#6]
As-salamu alaykum,

I'm using Firefox browser, on Debian 12.
Hamzatul wasl (ٱ) (in `README.md` file) doesn't render correctly, instead, it's being rendered as a box containing 4 numbers.

Image of hamzatul wasl rendering with me:
![Hamzatul wasl doesn't render in Debian Firefox](https://github.com/Muslim-Programmers/QuranApp-Linux/assets/70109144/071250fd-6843-4007-bc9b-4a512938f593)

Why is that?

I will edit `README.md` file to replace hamzatul wasl (ٱ) by alif letter (ا); since hamzatul wasl mostly being used in Quran mushafs, and alif letter in normal books.

**Comment by nxb1t** [comment]
Wa Alaikum Salam, Sorry for the late response.

**Comment by iTzVoko** [comment]
> Wa Alaikum Salam, Sorry for the late response.

No worries at all. Thanks for merging the changes.
